sudo: required

os:
  - linux

language: php

matrix:
    include:
        - php: 7.1
        - php: 7.2
        - php: 7.2
          env: deps=low

install:
  - |
    if [[ $deps = low ]]; then
        composer update --prefer-lowest
    else
        composer update
    fi

script:
  - composer lint
  - composer test
