version: 3.0.{build}

skip_tags: false

skip_non_tags: false

skip_commits:
  message: /Created.*\.(png|jpg|jpeg|bmp|gif)/      # Regex for matching commit message

max_jobs: 1

image: Visual Studio 2017

init:
  - git config --global core.autocrlf input

clone_folder: c:\projects\pact-php

install:
  - cinst php --version 7.0.27
  - cmd: C:\tools\php70\php.exe -i
  - cmd: copy /Y .\tests\PhpPact\php.ini C:\tools\php70\
  - appveyor DownloadFile https://getcomposer.org/composer.phar
  - cmd: C:\tools\php70\php.exe .\composer.phar update

build: off

test_script:
  - cmd: C:\tools\php70\php.exe .\composer.phar test

on_success:
  - echo Success

on_failure:
  - echo Failure