version: 4.0.{build}

skip_tags: false

skip_non_tags: false

skip_commits:
  message: /Created.*\.(png|jpg|jpeg|bmp|gif)/      # Regex for matching commit message

max_jobs: 1

image: Visual Studio 2017

init:
  - git config --global core.autocrlf input

install:
  - cinst php --version 7.2.1
  - set PATH=C:\tools\php72;%PATH%
  - cmd: copy /Y .\tests\PhpPact\php.ini C:\tools\php72\
  - cmd: php -v
  - appveyor DownloadFile https://getcomposer.org/composer.phar
  - cmd: php .\composer.phar update

build: off

test_script:
  - cmd: php .\composer.phar test

on_success:
  - echo Success

on_failure:
  - echo Failure